export const PORTFOLIO_ACTION_TYPES = {
  SET_PORTFOLIO_ITEMS: 'portfolio/SET_PORTFOLIO_ITEMS',
  FETCH_PORTFOLIO_MARKET_DATA_START: 'portfolio/FETCH_PORTFOLIO_MARKET_DATA_START',
  FETCH_PORTFOLIO_MARKET_DATA_SUCCESS: 'portfolio/FETCH_PORTFOLIO_MARKET_DATA_SUCCESS',
  FETCH_PORTFOLIO_MARKET_DATA_FAILED: 'portfolio/FETCH_PORTFOLIO_MARKET_DATA_FAILED',
}